### ISSUE TITLE
Issue with Werkzeug library version preventing Superset default installation

### ISSUE THREAD

**Issue by jortencio** [jortencio/superset#27]
Currently an issue installing Superset with default configurations due to dependency issue between Flask and Werkzeug library versions.  The version currently installed is Werkzeug version `3.0.4` which is not compatible with flask version `2.x.x`

Similar issue on [stackoverflow](https://stackoverflow.com/questions/77213053/why-did-flask-start-failing-with-importerror-cannot-import-name-url-quote-fr)

```
Notice: /Stage[main]/Superset::Init_db/Exec[Create Admin User]/returns: Traceback (most recent call last):
Notice: /Stage[main]/Superset::Init_db/Exec[Create Admin User]/returns:   File "/home/superset/apache-superset/bin/superset", line 5, in <module>
Notice: /Stage[main]/Superset::Init_db/Exec[Create Admin User]/returns:     from superset.cli.main import superset
Notice: /Stage[main]/Superset::Init_db/Exec[Create Admin User]/returns:   File "/home/superset/apache-superset/lib64/python3.8/site-packages/superset/__init__.py", line 18, in <module>
Notice: /Stage[main]/Superset::Init_db/Exec[Create Admin User]/returns:     from flask import current_app, Flask
Notice: /Stage[main]/Superset::Init_db/Exec[Create Admin User]/returns:   File "/home/superset/apache-superset/lib64/python3.8/site-packages/flask/__init__.py", line 7, in <module>
Notice: /Stage[main]/Superset::Init_db/Exec[Create Admin User]/returns:     from .app import Flask as Flask
Notice: /Stage[main]/Superset::Init_db/Exec[Create Admin User]/returns:   File "/home/superset/apache-superset/lib64/python3.8/site-packages/flask/app.py", line 27, in <module>
Notice: /Stage[main]/Superset::Init_db/Exec[Create Admin User]/returns:     from . import cli
Notice: /Stage[main]/Superset::Init_db/Exec[Create Admin User]/returns:   File "/home/superset/apache-superset/lib64/python3.8/site-packages/flask/cli.py", line 17, in <module>
Notice: /Stage[main]/Superset::Init_db/Exec[Create Admin User]/returns:     from .helpers import get_debug_flag
Notice: /Stage[main]/Superset::Init_db/Exec[Create Admin User]/returns:   File "/home/superset/apache-superset/lib64/python3.8/site-packages/flask/helpers.py", line 14, in <module>
Notice: /Stage[main]/Superset::Init_db/Exec[Create Admin User]/returns:     from werkzeug.urls import url_quote
Notice: /Stage[main]/Superset::Init_db/Exec[Create Admin User]/returns: ImportError: cannot import name 'url_quote' from 'werkzeug.urls' (/home/superset/apache-superset/lib64/python3.8/site-packages/werkzeug/urls.py)
```

**Comment by jortencio** [comment]
This is currently only an issue with older versions of Superset due to dependencies to older versions of Flask and Werkzeug.  The current release of this module (2.0.0) addresses this by updating the default Superset version to 4.0.2.
